global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:8080']
  - job_name: 'admin'
    static_configs:
      - targets: ['admin:8081']
